### ISSUE TITLE
Taiga ingots replace forge:ingots itemtag

### ISSUE THREAD

**Issue by MrWhiteEagle** [SpaceXVI/TAIGA#5]
Like the title says. on 1.16.5 all recipes that use the tag forge:ingots are replaced with taiga ingots. This is caused by taiga ingots having forge:ingots AND forge:ingots/material tag while other materials outside taiga have a single forge:ingots/material tag.

**Comment by SpaceXVI** [comment]
I surely overlooked that.. Alright, I'll try to release a fix for that in a few days, thanks for your help!

**Comment by MrWhiteEagle** [comment]
Youre welcome, im trying to fix it in crafttweaker though cuz its not something that can be ignored :D It f.e disallows making an ingot cast out of vanilla ingots. which locks the progression because it can only be made using taiga ores that need ingots which need an ingot cast, really funny if you think about it :D. Going to make the cast recipe craftable. For now.

PS. I am really impressed by such a fast response. Much appreciated

**Comment by MrWhiteEagle** [comment]
Also, are there any other tags that could get replaced like that i should know about???

**Comment by SpaceXVI** [comment]
Well, I heard that my vibranium conflicts with allthemods vibranium due to almost all my tags having the "replace" option on (I am gonna change that for some items next update), which in all honestly I couldn't care less about (in terms of vibranium) since ATM doesn't even use my mod in their packs and even then anyone can just simply change that.

**Comment by MrWhiteEagle** [comment]
Well, im using alltheores but its 1.16, that doesnt add the ATM ores to not ATM packs i think

**Comment by SpaceXVI** [comment]
I realized that not only does this affect ingots but dusts, crystals, nuggets, ores and storage blocks (iron blocks, gold blocks, etc..) too...
Oh and even better, fixing this also covers #1 

I am gonna mark this as fixed and hopefully release update 3.0.0, thanks for your help :)

**Comment by MrWhiteEagle** [comment]
Ok, i think i found a fix for you, the problem is that you set the tag to replace the existing one. So to fix you only need to change "replace": true to false and it should be all good.

**Comment by MrWhiteEagle** [comment]
Also, instead of making a list of all files separately, why not make a single file for ingots.json that contains all of the TAIGA ingots inside?

**Comment by MrWhiteEagle** [comment]
Ok, nevermind. Somehow even though i switched all ingot replace: true to false it still replaced forge:ingots itemtag i have no idea what is happening

**Comment by MrWhiteEagle** [comment]
I managed to fix it by changing all the replace to false inside the mod's data (sorry i meddled with it i guess) and the tags are listed correctly now [JESUS YES]

**Comment by MrWhiteEagle** [comment]
So, to make things straight. Vibranium is replaced in allthemods because of the forge/tags/ingots/vibranium.json is set to true, which replaces any vibranium tag in the ingots tag. The file under forge/tags/ingots.json however defines the items to be listed under the forge:ingots itemtag. Not the forge:ingots/vibranium tag F.E. When this ons is set to replace, it replaces the whole forge:ingots itemtag instead of just replacing any vibranium tag

**Comment by MrWhiteEagle** [comment]
What you need to do to fix this, is switch all of the forge/tags/tag.json files to NOT REPLACE IT, JUST ADD THEM TO THE TAG

**Comment by SpaceXVI** [comment]
Oh don't worry, I already did that before closing the issue, I just need to fix the other bugs in the mod before making an update, however.

**Comment by DonFlymoor** [comment]
Please update ASAP, the addon in unusable as is.

**Comment by SpaceXVI** [comment]
I mentioned this in my server already but I'll say it again, there's nothing I can currently do to any of my mods until mid-January (for like 1 week?) or post June, I am currently a 12th grader and managing time for coding is pretty hard in the meantime.
I apologize for halting my mods' progress and I am sorry I had to keep lots of people waiting, I really have no other choice.
